### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by RomarieQ** [ElevenfiftyAcademy/SystemShare#1]
In the CSS file:

@import url("https://overpass-30e2.kxcdn.com/overpass.css");

body {
  background-color: #284b63;
  color: #e2e4e7;
  font-family: "Arial";
  margin-left: 2em;
  -webkit-font-smoothing: antialiased;
}

#efalogo {
  font-weight: bold;
  margin-bottom: 2em;
}

input {
  border-radius: 4px;
  border-style: none;
  height: 20px;
  margin-bottom: 1em;
}

button {
  background-color: #f9f9f9;
  border: none;
  border-style: none;
  padding: 10px 10px;
  border-radius: 4px;
  text-decoration: none; 
}

In the HTML file:

<em>Don't worry, no computer is perfect!</em>

**Comment by AdamJayne** [comment]
Xzavier has made a push to his branch that will be created
